/**:
  ros__parameters:
    bag_filepath: "/media/haolei/P5/haolei/象山/数据备份/0804-data/202508041653/202508041653_0.db3"
    topic:
      image: "/zw040201/lq_camera"
      lidar: "/zw040201/lq_lidar_pointcloud"
    output_path:
      image: "/media/haolei/P5/haolei/象山/数据备份/0804-data/202508041653/images"
      lidar: "/media/haolei/P5/haolei/象山/数据备份/0804-data/202508041653/pointcloud"

    debug: true
    sync: true
